package com.ossys.ae.api.enums;

public enum ErrorCode {
	SUCCESS,					//
	ERROR_SYSTEM_FILE_NOT_FOUND,
	ERROR_DOMAIN_MODEL_NOT_FOUND,
	ERROR_PARSING_MODEL,
	ERROR_BUILDTOOL_NULL,
	ERROR_FRAMEWORK_NULL,
	ERROR_OTHER
}
